/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoRDeckMaster;

import no.stelar7.api.r4j.pojo.lor.staticdata.StaticLoRCard;

/**
 *
 * @author hoski
 */
public class CardPanel extends javax.swing.JPanel {

    private StaticLoRCard card;
    
    /**
     * Creates new form NewCardPanel
     */
    public CardPanel() {
        initComponents();
    }

    public void setCard(StaticLoRCard card) {
        this.card = card;
        jtfManaCost.setText(String.valueOf(card.getCost()));
        jtfCardName.setText(card.getName());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfManaCost = new javax.swing.JTextField();
        jtfCardName = new javax.swing.JTextField();

        jtfManaCost.setEditable(false);
        jtfManaCost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfManaCost.setText("0");
        jtfManaCost.setOpaque(false);

        jtfCardName.setEditable(false);
        jtfCardName.setText("CARD NAME");
        jtfCardName.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtfManaCost, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfCardName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jtfManaCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jtfCardName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jtfCardName;
    private javax.swing.JTextField jtfManaCost;
    // End of variables declaration//GEN-END:variables
}
