/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoRDeckMaster;

/**
 *
 * @author hoski
 */
public class DeckCardPanel extends javax.swing.JPanel {

    private DeckCard deckCard;
    
    /**
     * Creates new form DeckCardPanel
     */
    public DeckCardPanel() {
        initComponents();
    }

    public void setDeckCard(DeckCard deckCard) {
        this.deckCard = deckCard;
        jtfManaCost.setText(String.valueOf(deckCard.getCard().getCost()));
        jtfCardName.setText(deckCard.getCard().getName());
        jtfQuantity.setText(String.valueOf(deckCard.getQuantity()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfManaCost = new javax.swing.JTextField();
        jtfCardName = new javax.swing.JTextField();
        jtfQuantity = new javax.swing.JTextField();

        jtfManaCost.setEditable(false);
        jtfManaCost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfManaCost.setText("0");
        jtfManaCost.setOpaque(false);

        jtfCardName.setEditable(false);
        jtfCardName.setText("CARD NAME");
        jtfCardName.setOpaque(false);

        jtfQuantity.setEditable(false);
        jtfQuantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfQuantity.setText("0");
        jtfQuantity.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtfManaCost, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfCardName, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jtfManaCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jtfCardName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jtfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jtfCardName;
    private javax.swing.JTextField jtfManaCost;
    private javax.swing.JTextField jtfQuantity;
    // End of variables declaration//GEN-END:variables
}
